# Generated by Django 5.1.7 on 2025-07-31 09:53

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('last_id', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestRunCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('last_id', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('test_case_id', models.CharField(db_index=True, editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('ticket_id', models.CharField(blank=True, max_length=15, null=True)),
                ('title', models.CharField(max_length=100)),
                ('steps', models.TextField()),
                ('expected_result', models.TextField()),
                ('components', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=10)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('generated_by_ai', models.BooleanField(default=False)),
                ('source_similar_cases', models.TextField(blank=True, null=True)),
                ('has_playwright_script', models.BooleanField(default=False)),
                ('script_generated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ready', 'Ready for Testing'), ('automated', 'Automated'), ('manual_review', 'Needs Manual Review')], db_index=True, default='ready', max_length=20)),
            ],
            options={
                'db_table': 'test_case_tc',
                'ordering': ['-created_at'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['components'], name='test_case_t_compone_40b488_gin')],
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('test_run_id', models.CharField(db_index=True, editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('test_cases', models.ManyToManyField(related_name='test_run_tc', to='test_case.testcase')),
            ],
            options={
                'db_table': 'test_case_tr',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestRunCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('execution_failed', 'Execution Failed')], max_length=20)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('screenshot_path', models.CharField(blank=True, max_length=255, null=True)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_run_test_case', to='test_case.testcase')),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_run_test_cases', to='test_case.testrun')),
            ],
            options={
                'db_table': 'test_run_test_case',
                'ordering': ['test_run', 'test_case'],
                'unique_together': {('test_run', 'test_case')},
            },
        ),
    ]
