# Generated by Django 4.2.14 on 2025-08-13 06:52

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseCustomer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestCasePlatform',
            fields=[
                ('platform_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='testcase',
            name='test_case_t_compone_40b488_gin',
        ),
        migrations.AlterUniqueTogether(
            name='testruncase',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='components',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='generated_by_ai',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='has_playwright_script',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='script_generated_at',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='source_similar_cases',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='ticket_id',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='test_cases',
        ),
        migrations.AddField(
            model_name='testcase',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='preconditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='project',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='suite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_rail_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='tickets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, null=True, size=10),
        ),
        migrations.AddField(
            model_name='testcase',
            name='tr_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='tr_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testruncase',
            name='execution_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testruncase',
            name='execution_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testruncase',
            name='log_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testruncase',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='status',
            field=models.CharField(choices=[('ready', 'ready'), ('automated', 'automated'), ('manual_review', 'manual_review'), ('no_auto', 'no_automation_to_be_done')], db_index=True, default='ready', max_length=20),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='testcasecounter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testcasecounter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='testruncase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testruncase',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('passed', 'PASSED'), ('failed', 'FAILED'), ('skipped', 'SKIPPED'), ('in_progress', 'IN_PROGRESS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='testruncase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='testruncounter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testruncounter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tickets'], name='test_case_t_tickets_b02623_gin'),
        ),
        migrations.AddConstraint(
            model_name='testruncase',
            constraint=models.UniqueConstraint(fields=('test_run', 'test_case'), name='uniq_test_run_test_case'),
        ),
        migrations.AddField(
            model_name='testcasehistory',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_case.testcase'),
        ),
        migrations.AddField(
            model_name='testcasehistory',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='testruncase',
            name='execution_time',
        ),
        migrations.AddField(
            model_name='testcase',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='test_case_customers', to='test_case.testcasecustomer'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='test_case_platforms', to='test_case.testcaseplatform'),
        ),
        migrations.AddConstraint(
            model_name='testcasehistory',
            constraint=models.UniqueConstraint(fields=('test_case', 'version'), name='uniq_test_case_version'),
        ),
    ]
