# Generated by Django 5.1.7 on 2025-08-13 07:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_case', '0002_testcasecustomer_testcasehistory_testcaseplatform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='status',
            field=models.CharField(choices=[('ready', 'ready'), ('automated', 'automated'), ('manual_review', 'manual_review'), ('no_auto', 'no_automation_to_be_done')], db_index=True, default='ready', max_length=50),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='test_case_id',
            field=models.CharField(db_index=True, editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='test_rail_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='tickets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=10),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='testcasecustomer',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='testcaseplatform',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='testruncase',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('passed', 'PASSED'), ('failed', 'FAILED'), ('skipped', 'SKIPPED'), ('in_progress', 'IN_PROGRESS')], max_length=50),
        ),
    ]
