# Generated by Django 5.1.7 on 2025-08-18 11:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_case', '0004_alter_testcase_expected_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='project',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='status',
            field=models.CharField(choices=[('ready', 'ready'), ('automated', 'automated'), ('manual_review', 'manual_review'), ('no_auto', 'no_automation_to_be_done')], db_index=True, default='ready', max_length=100),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='suite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='test_case_id',
            field=models.CharField(db_index=True, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='test_rail_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='tickets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=10),
        ),
    ]
